### PR TITLE
Update tblib version for pytest compatibility

### PR DESCRIPTION
**Pull request by imachug**

### CODE REVIEW

**Comment by imachug** [comment]
I'm not sure why Travis CI is failing, it is most likely unrelated to the PR.

**Comment by imachug** [comment]
@jamadden Any update on this PR?

**Comment by imachug** [comment]
Should the build be failing or can it be caused by my PR?

**Comment by jamadden** [comment]
It's not caused by this. There are some unrelated SSL issues that are tricky to reproduce and which will take some debugging on my part (they're almost certainly problems in the test suite).

**Comment by imachug** [comment]
Thanks, I just wanted to make sure my PR doesn't break anything.

**Pull request merged**
