### PR TITLE
Fix pypy3 imports

### PR DESCRIPTION
**Pull request by utzig**
In pypy3 import from `_thread` (python3) instead of `thread`.

### CODE REVIEW

**Comment by jamadden** [comment]
Thank you for the PR and the interest in PyPy(3).

Sadly, we don't actually test on or support PyPy 3 at this time...the released versions of PyPy3 have the Python 3.2 stdlib, and the minimum supported version for gevent is Python 3.3.

I know that work is progressing for an updated PyPy3, and when one comes out that supports a more recent stdlib I'll gladly add it to the build matrix. But until then, this would just be dead code inviting bitrot, unfortunately.

**Comment by jamadden** [comment]
Well heck, so I guess they've put out [an alpha](http://doc.pypy.org/en/latest/release-pypy3.3-v5.2-alpha1.html). I wonder if there are the portable linux images we need for it...

**Comment by utzig** [comment]
You're correct, I'm using the alpha version which supports 3.3! https://morepypy.blogspot.com.br/2016/05/pypy33-v52-alpha-1-released.html

Anyway the patch is very simple and is working for me for both versions.

**Comment by utzig** [comment]
I'm on a Mac. Did not test on Linux yet.

**Comment by jamadden** [comment]
Were you able to run the complete test suite?

**Comment by utzig** [comment]
I did not try but can do.

**Comment by jamadden** [comment]
Yeah, that'd be the next step to get an idea of how complete it is for gevent's purposes:
```
cd src/greentest && GEVENT_RESOLVER=thread pypy3 testrunner.py --config known_failures.py
```

**Comment by utzig** [comment]
https://gist.github.com/06be9e45781a279af74831384e74d93b

**Comment by jamadden** [comment]
Thanks. So there's some work to do 😦 Some of those I remember from PyPy2 ('no such attribute timeout') but the actual hangs/timeouts aren't ringing any bells.

**Comment by jamadden** [comment]
I myself do not currently have the time to follow up on these issues with PyPy3. I will personally consider them higher priority when a *beta* release comes out.

I would review a PR that fixed them and added a Travis test environment for it, but that's about the extent for me right now.

If some time opens up before the beta arrives I'll try to spend some time on this.

I'll leave this open as a reminder that it's not currently supported and work needs to be done.

**Pull request closed without merging**
