### PR TITLE
Per gevent/gevent#546, rebase the changes on top of gevent 1.0.2. Fixes gevent/gevent#477.

### PR DESCRIPTION
**Pull request by jamadden**
I tested on both 2.7.8 and 2.7.9 with these results:

```
2/120 unexpected passes
 - /Python -u -m monkey_test --Event test_ssl.py
 - /Python -u -m monkey_test test_ssl.py

6/120 tests failed in 01:18

6/120 unexpected failures
 - /Python -u -m monkey_test --Event test_httpservers.py
 - /Python -u test_ares_timeout.py
 - /Python -u test__socket_dns6.py
 - /Python -u test__socket_dns.py
 - /Python -u -m monkey_test test_httpservers.py
 - /Python -u test__all__.py
```

The `httpservers` failure is because it relies on the internals of the CGI module that have now been moved. The DNS failures are due to differences in DNS configuration. `test_ares_timeout` is because it tries to bind to port 53, which doesn't work for non-root users under unix, and to detect this it relies on a specific error message which has either changed or varies between platforms. `test__all__` complains about `test_libev`, and I have no idea what that's about.

Notably, the `test_ssl` passes now on both 2.7.8 and 2.7.9. I didn't mess with the known_failures list because I didn't test under 2.6.

### CODE REVIEW

**Comment by sprin** [comment]
:clap:

I am happy to review this weekend.

It sounds like `test_ares_timeout` should just be skipped by default if it tries to bind to a privileged port. It might make sense to keep it enabled if the tests were always running in a defined container/VM, but having a test that requires root does not make sense when most devs are probably running tests in an unprivileged venv.

We should look at the other tests to see if it makes sense to fix or disable them. I would suggest that tests that are sensitive to DNS config also don't make sense in the typical case.

**Comment by jamadden** [comment]
Disabling `test_ares_timeout` is what I eventually did in #552...although, looking more closely at the underlying ares code now, it seems like there might be a way to actually specify a port to use, so it may be possible to make it pass. I'll look into that.

I keep saying the DNS tests are config/remote server dependent because sometimes I see them pass and sometimes (usually) they don't. I'd hate to disable them entirely, though, because it seems like they're testing an important part of the codebase (they run, just get slightly different output than expected). Perhaps there's a way to make them more tolerant of differences but still check the codepaths. I'll look into that too.

If I find anything I'll open a different PR.

**Comment by jamadden** [comment]
Oh, also, I'm pretty sure the `test__all__` failure with 'libev' is just an artifact of re-using a build directory for master on PyPy and this branch on CPython; a pseudo-module gets created for the benefit of PyPy on master that I hadn't cleaned up.

**Comment by jamadden** [comment]
I did find a better way to fix `test_ares_timeout`, `test_httpservers` and the DNS tests; I put those in a PR against master to keep this one as small as possible. But if requested I can put those changes here too.

In #477 some comments state that certain distributions have backported the SSL changes *without* changing the python version number (i.e., it's still 2.7.8). It would probably be easy to make this `ssl` module detect that and not just be driven off the version number. I can add that if desired, but it might be tricky to verify.

Please let me know if I can help move this forward in any way. In addition to #477, this should resolve #513 and #545.

**Comment by jamadden** [comment]
@sprin and @ivoz any thoughts?

**Comment by jamadden** [comment]
@sprin  @Ivoz Is this the major blocker for a 1.0.2 release? If so, we should probably try to get this out there sooner rather than later. (I'm not aware of a roadmap, that's something that should probably be discussed at some point.)

**Comment by jamadden** [comment]
@sprin @ivoz I skipped the style checks to run the actual tests on Travis. Python 2.6 is clean. Python 2.7 had one timing related failure that is *probably* transient. Python 2.5 is currently blocked on python-greenlet/greenlet#82 and won't run; our options, as I see them, are to wait for a new release of greenlet, or to pin it to 0.4.5 under Python 2.5 (not good because it clashes when it does get fixed) or ignore the issue.

**Comment by jamadden** [comment]
The build is now green across the board for 2.5, 2.6 and 2.7. Unless there are any objections, I will probably merge this soon.

**Comment by thedrow** [comment]
Woot! Well done.

**Comment by guilbep** [comment]
Yeahh gevent 1.0.2 fixed it :) :+1:

**Pull request merged**
