### PR TITLE
Suppress EPIPE and ECONNRESET tracebacks properly

### LINKED ISSUE #136: pywsgi: shouldn't spew debugging data for normal network and timeout errors
pywsgi spews lots of debugging information for &quot;connection reset by
peer&quot; and &quot;broken pipe&quot;.  This seems to be done in Hub.handler_error,
which is called on pretty much any error from
WSGIHandler.handle_one_response.

&quot;connection reset by peer&quot;, &quot;broken pipe&quot; and timeout errors on HTTP
sockets shouldn't cause debugging output.

In addition to causing large log files to be created, these noise errors can hide important errors.<p><a href="http://code.google.com/p/gevent/issues/detail?id=136">Reported by j1mf4n.</a></p>

### PR DESCRIPTION
**Pull request by pshc**
The exception handler in `handle_one_response()` was catching and dumping socket errors before the handler in `handler_one_request()` ever got to see them and squash their tracebacks. So, I just moved the exception handler over to `handle_one_response`.

Fixes #136.

### CODE REVIEW

**Comment by jetz** [comment]
same problem for long polling after client (eg. browser) close, so +1

**Comment by pshc** [comment]
C'mon @gevent, what do you think? It's been a year.

**Comment by jetz** [comment]
@pshc I wonder if it's a problem to ignore all EPIPE, ECONNRESET errs at framework level? So I just patch the BaseServer in my project, like [this](https://gist.github.com/jetz/2fc9b408209512b094f4)

**Comment by trainiac** [comment]
:+1:

**Comment by maxcountryman** [comment]
:+1:

**Comment by fgimian** [comment]
+1 please

**Comment by pshc** [comment]
👏✌️

**Comment by parasyte** [comment]
:tada: Thanks for this! (It has been bugging me for years.)

**Comment by fxah** [comment]
Happened to me on an SSE service with bottle. All is well now. :heart:

**Pull request merged**
