### PR TITLE
appveyor.yml: Test on Python 3.13 release candidate

### PR DESCRIPTION
**Pull request by cclauss**
* https://www.python.org/download/pre-releases
* https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#allow-pre-releases

> Building wheel for greenlet (pyproject.toml): finished with status 'error'

Blocked by:
* #2037
* python-greenlet/greenlet#396

### CODE REVIEW

**Comment by EwoutH** [comment]
I know this configuration uses a Windows image, but FYI: AppVeyor now ships their Ubuntu images with the latest Python 3.13:
- https://github.com/appveyor/ci/issues/3927

**Comment by cclauss** [comment]
Thanks @EwoutH. I have been keeping the Appveyor's examples for Python up to date over the years so I understand its capabilities.  The important aspect of this PR is not which OS it is running on.  Instead, it is that we have a working example of `python3.13 -m pip install greenlet` fails on ___all___ operating systems.

This proves that python-greenlet/greenlet#396 is required for greenlet, event, and numerous other projects to work on Py3.13.
* python-greenlet/greenlet#396

**Comment by cclauss** [comment]
This can be revisited once there is a new release of greenlet
* https://github.com/python-greenlet/greenlet/tags

**Comment by jamadden** [comment]
Thanks, fixed in another commit.

**Pull request closed without merging**
