### PR TITLE
Implement gevent.select.epoll

### PR DESCRIPTION
**Pull request by hashbrowncipher**
When running with gevent monkeypatching beneath an asyncio eventloop, gevent provides asyncio with PollSelector since 3d4404d (before that, it provided SelectSelector). Both implementations are "stateless": they do not cache io watchers, so they must re-add the watchers each time their respective `poll()` functions are called, burning CPU time on `epoll_ctl` syscalls. An `epoll` interface can keep a stable set of I/O watchers. By doing so, it minimizes syscalls.

uvicorn workload before:

```
epoll_wait(6, [], 262, 0)               = 0
getpid()                                = 27041
getpid()                                = 27041
epoll_ctl(6, EPOLL_CTL_ADD, 9, {EPOLLIN, {u32=9, u64=339302416393}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 17, {EPOLLIN, {u32=17, u64=12884901905}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 21, {EPOLLIN, {u32=21, u64=8589934613}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 23, {EPOLLIN, {u32=23, u64=8589934615}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 24, {EPOLLIN, {u32=24, u64=8589934616}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 26, {EPOLLIN, {u32=26, u64=8589934618}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 27, {EPOLLIN, {u32=27, u64=8589934619}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 28, {EPOLLIN, {u32=28, u64=8589934620}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 29, {EPOLLIN, {u32=29, u64=8589934621}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 31, {EPOLLIN, {u32=31, u64=8589934623}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 32, {EPOLLIN, {u32=32, u64=8589934624}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 34, {EPOLLIN, {u32=34, u64=8589934626}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 36, {EPOLLIN, {u32=36, u64=8589934628}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 37, {EPOLLIN, {u32=37, u64=8589934629}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 38, {EPOLLIN, {u32=38, u64=8589934630}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 39, {EPOLLIN, {u32=39, u64=8589934631}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 40, {EPOLLIN, {u32=40, u64=8589934632}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 41, {EPOLLIN, {u32=41, u64=8589934633}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 42, {EPOLLIN, {u32=42, u64=8589934634}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 43, {EPOLLIN, {u32=43, u64=8589934635}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 44, {EPOLLIN, {u32=44, u64=8589934636}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 45, {EPOLLIN, {u32=45, u64=8589934637}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 46, {EPOLLIN, {u32=46, u64=8589934638}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 47, {EPOLLIN, {u32=47, u64=8589934639}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 48, {EPOLLIN, {u32=48, u64=8589934640}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 49, {EPOLLIN, {u32=49, u64=8589934641}}) = -1 EEXIST (File exists)
epoll_ctl(6, EPOLL_CTL_ADD, 50, {EPOLLIN, {u32=50, u64=8589934642}}) = -1 EEXIST (File exists)
[hundreds more lines]
```

uvicorn workload after:

```
epoll_wait(6, [], 64, 0)                = 0
getpid()                                = 13661
getpid()                                = 13661
epoll_wait(6, [], 64, 100)              = 0
getpid()                                = 13661
epoll_wait(6, [], 64, 0)                = 0
```

### CODE REVIEW

**Comment by jamadden** [comment]
Thank you for the patch. It's very unlikely to be accepted, though. In addition to the tests that are broken, please see the discussion of https://github.com/gevent/gevent/issues/962. In short, there are a *lot* of things that `select.epoll` needs to be able to do that require expensive emulation (or simply aren't possible).

**Comment by hashbrowncipher** [comment]
Having now re-read gevent #962, I agree that there's no way to provide an implementation identical to Python's `select.epoll()`, so the PR in its current form may be too ambitious. It sounds like you're concerned about the project being on the hook to maintain an epoll-compatible API. Perhaps we can sidestep those issues by not actually exposing the interface to anything except the `selectors` library.

Specifically: what if we scaled back the API surface to simply "provide `selectors.GeventSelector` and make `selectors.DefaultSelector=selectors.GeventSelector`"? Doing so would allow for a "best of both worlds" scenario, where gevent monkeypatching can be used with asyncio, with performance approaching that of non-monkeypatched code.

**Comment by jamadden** [comment]
I think adding `gevent/selectors.py` which imports-and-reexports all the standard library `selectors` API, plus adds a `GeventSelector` that uses persistent watchers is a great idea. A bunch of what's in `gevent/select.py:_gevent_do_monkey_patch` relating to selectors could be moved to a similar function in the new module, and some small changes would be needed to `gevent/monkey.py:patch_all`, notably the addition of `patch_selectors(aggressive=True)`. Some updates to the documentation would be needed as well. I think we'd also want our own `test__selectors.py` (probably initially derived from the standard library one) to test the `GeventSelector` independently of monkey-patching.

I'm not sure about making the `GeventSelector` the default selector, though. The reason is that now libev and libuv both can be or are aggressive about crashing the process if a file descriptor gets closed while a watcher is open. It seems like keeping watchers open for longer is more likely to cause issues.

However: it's probably easier to roll that back if we get reports of crashes than it is to make it the default in a future point release, so I'd say it's worth giving that a try too.

Spelling that all out makes it sound like quite a bit, and a lot of it is finicky details, so I understand completely if you're not interested in working on it. But if you would like to work on some or all of it please let me know; otherwise I'll put it near the top of my TODO list.

**Comment by hashbrowncipher** [comment]
Awesome! I agree with you that many of the details sound finicky, and I'm happy to have you tackle them instead of me. In the meantime, I have deployed my own GeventSelector based on the code in this PR; I have a production use-case running against it and will be on the look-out for any bugs. With #1532 now open, does it make sense to close this PR?

**Pull request closed without merging**
