### PR TITLE
Enable ccache to shorten build times

### PR DESCRIPTION
**Pull request by thedrow**
I was sure I contributed it but I didn't. It should be an easy win.

### CODE REVIEW

**Comment by jamadden** [comment]
Without also forcing make and the like to use the `ccache` binary instead of `gcc`, I don't think this is going to do anything. For some parts of some builds it may be enough to `export CC=ccache`, but it's not clear to me that that would do handle everything.

**Comment by thedrow** [comment]
It seems like it didn't. I'll make sure it does.

**Comment by thedrow** [comment]
@jamadden I don't think the build failure is related.

**Comment by jamadden** [comment]
It appears that in the best cases, this might possibly save maybe 20 seconds or so. But there's so much variability in our build times already that it's hard to be sure.

It was definitely worth a try (thanks!), but since the win is so small, I'd be inclined to not merge this: I'd prefer not to introduce more differences between local development and the CI environments than we have to, and I'm not going to try to bother with installing ccache locally 😄

**Comment by thedrow** [comment]
ccache doesn't affect anything other than compilation times. I don't think it's a big deal that your development environment doesn't have it.
I'll close the PR for now. If you reconsider, reopen and merge it.

**Pull request closed without merging**
