### PR TITLE
PyPy 2.5.1 support improvements

### PR DESCRIPTION
**Pull request by jamadden**
As per the discussion in #248, this branch, including commits from others including @parasyte and @sprin brings much improved PyPy support to `master`. The results from a PyPy 2.5.1 run:

```
4/123 tests failed in 02:53

4/123 expected failures
 - //pypy/bin/pypy -u -m monkey_test test_socket.py
 - //pypy/bin/pypy -u -m monkey_test --Event test_socket.py
 - //pypy/bin/pypy -u test__socket_dns6.py
 - //pypy/bin/pypy -u test__threading_vs_settrace.py
```

Compare with the results from a CPython 2.7.9 run:

```
1/123 tests failed in 01:51

1/123 expected failures
 - //python2.7 -u test__socket_dns6.py
```

### Notable changes

* The SSL support for Python 2.7.9 is included (from #546). This is necessary because PyPy 2.5.0 crashes frequently using cFFI, and PyPy 2.5.1, which does work, includes the Python 2.7.9 stdlib.
* The `stat` watcher is implemented.
* Socket servers deterministically close their socket when done handling a request. On CPython they would immediately be cleaned up due to reference counting, but under PyPy we'd be at the mercy of the GC. @tilgovi confirmed that gunicorn closes them anyway already.
* Other than that, it's mostly minor bugfixes and additions.

### Expected failures under PyPy

* The expected failures in `test_socket` are due to https://bitbucket.org/cffi/cffi/issue/152/handling-errors-from-signal-handlers-in
* The expected failures in `test__socket_dns6` are due to different DNS server configurations returning different answers and/or changed data. Note this also fails in CPython.
* `test__threading_vs_settrace`, as noted in `known_failures.py` fails because the Semaphore is not compiled with cython. It is possible to compile it with cython under PyPy, and the tests all do run like that, including this one. It will take a bit of re-naming to make that work, though and I didn't know if the benefits were worth it.

I realize this is probably a rough PR. I'm willing to help in the best way needed to keep helping move PyPy support forward.

### CODE REVIEW

**Comment by jamadden** [comment]
I included the changes from #553 in this PR as well. Now, **CPython has 0** expected failures, and PyPy has only 3.

**Comment by tilgovi** [comment]
@jamadden thanks so much for your efforts. Here's hoping this can merge soon.

**Comment by sylvinus** [comment]
Congrats for all the work, looking forward to this.

**Comment by jamadden** [comment]
With this PR (plus some other upstream changes) we've been able to successfully run a large benchmark (specifically ZODB/ZEO) under PyPy+gevent. Details are in [this comment](https://github.com/zopefoundation/persistent/pull/20#issuecomment-95611745). 

Please let me know if I can help move this forward in any way.

**Comment by jamadden** [comment]
@denik @Ivoz any thoughts on how I can help with this?

**Comment by jamadden** [comment]
I think I need to back out the first commit; that was before the epic work @sprin did to bring full 2.7.9 support to the ssl module.

**Comment by jamadden** [comment]
The build is now green across the board for PyPy, 2.6, 2.7 and 3.3. Unless there is feedback or objections I will plan to merge this shortly after #551 merges to keep SSL support in sync.

**Pull request merged**
