### PR TITLE
Workaround a memoryview leak in py2

### PR DESCRIPTION
**Pull request by damz**
See #1318

### CODE REVIEW

**Comment by jamadden** [comment]
Thanks for the PR. Given the substantial slow down this has for the normal case, I would prefer to find a different solution.

**Comment by jamadden** [comment]
`_get_memory` is in a pure-Python module (gevent._socket2), so you could monkey-patch that function to this version in the interim.

**Comment by damz** [comment]
@jamadden We are not currently affected, we workaround that differently (by removing the `io.BufferedWriter` that was actually completely unnecessary in this case).

**Comment by jamadden** [comment]
> @jamadden We are not currently affected, we workaround that differently (by removing the io.BufferedWriter that was actually completely unnecessary in this case).

Cool, good to know! Thanks again for the report!

**Pull request closed without merging**
