### PR TITLE
Replace optparse with argparse

### LINKED ISSUE #947: Transition away from optparse
Now that we require 2.7+, we should stop using the deprecate optparse and replace it with argparse.

There are two uses:
* src/greentest/testrunner.py
* src/greentest/bench_spawn.py

### PR DESCRIPTION
**Pull request by renstrom**
Fixes #947

### CODE REVIEW

**Comment by jamadden** [comment]
Thanks! Feel free to add a note to CHANGES.rst.

Unfortunately, the arguments for testrunner.py [aren't quite correct](https://travis-ci.org/gevent/gevent/jobs/209743560#L888) (the test argument needs to be completely optional).

**Comment by renstrom** [comment]
Done and done!

**Comment by renstrom** [comment]
Not sure what do make of the failed test though. Flaky?

**Comment by jamadden** [comment]
Yeah, the timeout-based tests are occasionally flakey on CI. I'm running it again.

**Pull request merged**
