### PR TITLE
Use a manually locked pure-Python Semaphore implementation on PyPy

### PR DESCRIPTION
**Pull request by jamadden**
Issue #704 and the ensuing [discussion on the PyPy bugtracker](https://bitbucket.org/pypy/pypy/issues/2209/segfault-while-running-our-uts-after) detail an *extremely* easy-to-reproduce crash involving the interaction between Cython compiled objects (in general, any object using the cpyext api) and the PyPy garbage collector. Because of that and other issues we've encountered with PyPy and the cpyext API, such as memory leaks, this PR proposes that we stop compiling the Semaphore with cython and go back to a pure-python implementation.

What are the implications?

First, raw speed. Under CPython presumably Cython is an improvement, but under PyPy it is not. In testing `sem.acquire();sem.release()` with `timeit`, the Cython version clocks in at 5usec per iteration, while the version we end up with here comes in at 0.262usec, a substantial improvement (and of the same order of magnitude as the CPython+Cython time of 0.141usec). So we're good there.

Second, thread safety. Because the Cython compiled methods are called with the GIL held, and never release them, each method was implicitly threadsafe and automatically non-reentrant. There's never an opportunity for a thread switch to occur while a Cython method is running until it calls into a pure-python method or returns. (The semaphore does make some calls to `get_hub` which would allow a thread switch but only when we're in a stable state.) As for greenlets on the same thread, the semaphore carefully manages its switches.

If we don't compile with Cython, we need to do something else to be thread safe. This implementation wraps a native thread lock around the critical methods that manipulate the counter: `wait`, `acquire` and `release`, being careful to drop the lock when we go to sleep in the hub. Although it would be nice use a single lock instead of one per instance to both match the GIL semantics and keep overhead as low as possible, we can't do that (see below) (note that in the timeit tests, the per-instance lock and context manager system in use now performs about well as a simpler global strategy).

I *suspect*, but haven't confirmed, that there may be a race condition with signal handlers trying to acquire a Semaphore at the same time that normal code tries to acquire it, leading to a deadlock. That seems unlikely to me, though.

Finally, `test__threading_vs_settrace` and its original version in the python test suite, `test_threading:test_finalize_with_trace`. Both of them ensure that a tracing function that accesses `threading.current_thread()` during interpreter shutdown do not hang. This refers to a bug in the interpreter's threading implementation that was fixed for 2.6 (and so doesn't really concern us). The gevent test case goes further to say that no tracing function should ever see the workings of Semaphore, which is easy to ensure with Cython, and pretty much impossible otherwise.

I've scratched my head over that quite a bit and tried various recursive-lock-like strategies to minimize any interference that a tracing function might have, but I don't think it's possible to be perfect. The current solution works as expected on tracing a lock function when the trace function uses no locks or when the trace function uses a different lock. When the trace function tries to acquire or release the same lock that is being traced, a LoopExit is raised; that seemed better than the alternative which was to deadlock. (Ack, just realized that the last change to make that work probably broke the multi-threaded semantics so I need to add a new commit, but I'm opening this PR now for review.)

Comments, feedback, alternate ideas very welcome!

### CODE REVIEW

**Comment by jamadden** [comment]
I think I fixed the threading reentrancy problem. It slows down the semaphore to 0.5usec, but otherwise all the tests pass.

**Comment by thedrow** [comment]
Can't we implement the lock in C using CFFI?

**Comment by thedrow** [comment]
Also, I think we're discovering more and more that we need to implement #580 or disable c-ares on PyPy just to avoid crashes.

**Comment by jamadden** [comment]
> Can't we implement the lock in C using CFFI?

Indeed, that was my original intent (thus the name of the branch). That turns out to be rather ugly and more involved than this approach though, I think. The entirety of `acquire`, `wait` and `release` have to be implemented in C, making callbacks to Python (well, I say "entirety", but there still has to be a thin Python wrapper that sets up the call into C). There has to be an additional C struct containing an integer to hold the value that's manipulated in C, and the value synced with what's visible from the Python side.

The Semaphore class is relatively complex and widely used, and I don't want a completely separate implementation of it, at least not this late in the game, so that all has to be accomplished by monkey-patches, similar to what's being done in this PR.

Finally, while the C functions would be suitably atomic, it's not clear if they would hold the GIL or not, meaning we may still need a lock. C function calls are [documented as *dropping* the GIL](http://cffi.readthedocs.org/en/latest/using.html) but that may only apply to function pointers; it's not totally clear to me.

**Comment by jamadden** [comment]
>  disable c-ares on PyPy just to avoid crashes.

I think the documentation is pretty clear about the possible risks of using the ares resolver on PyPy. Because it's optional and not on by default, I don't see a lot of benefit in removing the capability entirely; indeed, using Semaphore through Cython has led to the detection of a number of PyPy bugs---they can't know about bugs in code that's not being used.

I also think that the ares resolver has a much different usage pattern than Semaphores do. A typical program will create exactly *one* instance of a Cython-compiled class that lives for the duration of the program so the GC interactions should be eliminated. Clients should never actually be dealing with any of the Cython-compiled code, only our wrapper in resolver_ares.py so we're free to make adjustments/workarounds there as necessary.

**Pull request merged**
