### PR TITLE
Use a requirements file to make dev easy

### PR DESCRIPTION
**Pull request by Ivoz**
Setting up packages needed for hacking can now just be ~one step

### CODE REVIEW

**Comment by jamadden** [comment]
That looks pretty reasonable. It used to be simpler but dependencies have grown/gotten more specific recently. 

I figure you tested those steps locally?

Also, should we mention something about virtualenvs in that block?

**Comment by Ivoz** [comment]
> Also, should we mention something about virtualenvs in that block?

Hmmm, true. Assumed knowledge on my part.

**Comment by Ivoz** [comment]
There, look better?

(rebase showing commits I've rebased ontop of master, when I'm trying to push into master.. w/e github)

**Comment by jamadden** [comment]
Any particular reason for the changes to tox.ini?

**Comment by Ivoz** [comment]
The PR is showing all the commits, including the ones already on master. I'll resubmit it

**Comment by Ivoz** [comment]
Ok, new one still shows 5 commits.

https://github.com/gevent/gevent/commit/c9d347bb835cc1d6eb41474770a2e962bf742c07 is the `tox.ini` one

**Pull request merged**
