### PR TITLE
for 32-bit build on 64-bit linux, grab CFLAGS -m32 from python.sysconfig

### PR DESCRIPTION
**Pull request by lanstin**

### CODE REVIEW

**Comment by jamadden** [comment]
Hmm, I'm not sure about this. Won't that override the value that the user has set in the environment? E.g., some ARM users are finding that they need to disable optimizations by setting -O0 (#543) (sometimes I need to do that when debugging).

**Comment by lanstin** [comment]
I only look at whether or not -m32 was used in the python build, not any other compiler settings.  Checking the build failure.

**Comment by lanstin** [comment]
Fixing build failures, so will push another commit to PR (or would you prefer new PR with squashed?)  It seems Python 2.6 lacks sysconfig module, so I'll need to think about that.  

Also, I can make it so that we preserve existing CFLAGS env variable, and just add -m32 in that case.

**Comment by jamadden** [comment]
> or would you prefer new PR with squashed?

Personally, I'm not big on squashing away history. Yes it makes things "cleaner", but it also throws out the steps that it took to get from non-working to working, and sometimes those steps contain important lessons.

**Comment by lanstin** [comment]
Everything is green but the testing build with python 3.4 which has this error:

                   stderr=STDOUT)
  Expected:
      b'ls: non_existent_file: No such file or directory\n'
  Got:
      b'ls: cannot access non_existent_file: No such file or directory\n'

Which I believe is a change to the /bin/ls program not python per se.  

https://github.com/goj/coreutils/commit/3a208b14048121755eb01377f985372561a4b953#diff-3a7e15506b2a0bc55177b8d159cf98a8R2614

So I think it's ok.  It will not remove items from the CFLAGS (and this change only affects config time for c-ares, not compile time nor any other config time).

**Pull request merged**
