### PR TITLE
Support coverage.py in the testrunner and coveralls.io

### PR DESCRIPTION
**Pull request by jamadden**
Experimental.

### CODE REVIEW

**Comment by nedbat** [comment]
This makes me happy :)

**Comment by jamadden** [comment]
It makes me happy too. Thank you! Now if I could just figure out why [`__init__.py`](https://coveralls.io/builds/3593141/source?filename=gevent%2F__init__.py) looks so weird (I thought using concurrency=gevent automatically turned on timid mode?). I haven't reproduced it locally on OS X but I also haven't tried that hard yet :)

**Comment by jamadden** [comment]
I meant "turned off" timid mode---I tried turning it on and found out that it's not allowed :) I *can* reproduce it on OS X, which is half the battle. Now I just have to figure out why.

**Comment by nedbat** [comment]
It looks like `__init__.py` is being imported before you start coverage.

**Comment by jamadden** [comment]
That's what I thought, but so far, logging seems to reveal that sitecustomize.py is truly imported before __init__.py in all the subprocesses. There's the same problem (top level statements being marked uncovered)  with things like hub.py too.

**Comment by jamadden** [comment]
D'oh! coverage.py itself imports gevent before beginning to trace when `concurrency` is set to `gevent`. So all the top-level statements in `__init__.py` (and in everything it imports) have already been executed by the time tracing kicks in.

Backtrace:
```
(Pdb) bt
  //bin/coverage(11)<module>()
-> sys.exit(main())
  //lib/python3.4/site-packages/coverage/cmdline.py(694)main()
-> status = CoverageScript().command_line(argv)
  //lib/python3.4/site-packages/coverage/cmdline.py(435)command_line()
-> return self.do_run(options, args)
  //lib/python3.4/site-packages/coverage/cmdline.py(565)do_run()
-> self.coverage.start()
  //lib/python3.4/site-packages/coverage/control.py(670)start()
-> self._init()
  //lib/python3.4/site-packages/coverage/control.py(248)_init()
-> concurrency=concurrency,
  //lib/python3.4/site-packages/coverage/collector.py(100)__init__()
-> import gevent                   # pylint: disable=import-error,useless-suppression
  <frozen importlib._bootstrap>(2237)_find_and_load()
  <frozen importlib._bootstrap>(2226)_find_and_load_unlocked()
  <frozen importlib._bootstrap>(1200)_load_unlocked()
  <frozen importlib._bootstrap>(1129)_exec()
  <frozen importlib._bootstrap>(1471)exec_module()
  <frozen importlib._bootstrap>(321)_call_with_frames_removed()
> //gevent/__init__.py(11)<module>()
```

It looks like the only thing that the `gevent` import is used for is `gevent.getcurrent`. But that happens to be just an alias for `greenlet.getcurrent`, so it looks to me like setting `concurrency` to `greenlet` should be equivalent to using `gevent` and sidestep this problem entirely. I'll try.

**Comment by jamadden** [comment]
That seems to have done it!

**Pull request merged**
