### PR TITLE
Upgraded c-ares to 1.10.0

### LINKED ISSUE #574: Upgrade the bundled c-ares to 1.10.0
I have not seen a problem with the current version of c-ares but it's nice to have since the new version fixes a memory leak and have other minor bug fixes.
See the [release notes](https://github.com/bagder/c-ares/blob/cares-1_10_0/RELEASE-NOTES) for the full list of changes.

### PR DESCRIPTION
**Pull request by thedrow**
Fixes #574

### CODE REVIEW

**Comment by jamadden** [comment]
LGTM. The PyPy test failure is unrelated (test__refcount is sometimes flaky). Can you add a changelog entry please?

**Comment by thedrow** [comment]
Yes sure.

**Comment by thedrow** [comment]
@jamadden Done.

**Comment by jamadden** [comment]
Thank you!

**Comment by thedrow** [comment]
No problem :)

**Pull request merged**
